// AUTO-GENERATED by scripts/fetch-images.mjs — do not edit by hand.
export interface ImageAsset { src: string; width: number; height: number; blurDataURL: string; alt: string;
  credit: { photographer: string; photographerUrl: string; sourceUrl: string; provider: "Pexels"; photoId: number } }
export const images = {
  "hero": {
    "src": "/images/marketing/hero-poster.jpg",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAALABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAgT/xAAbEAACAwEBAQAAAAAAAAAAAAABAgADERIEE//EABUBAQEAAAAAAAAAAAAAAAAAAAID/8QAFxEBAAMAAAAAAAAAAAAAAAAAAQARMf/aAAwDAQACEQMRAD8Ajq9DisaRF9WsbklZMiK1SFhsXCjGAw7GpeSQNbP/2Q==",
    "alt": "A mobile groomer with a freshly groomed fluffy dog",
    "credit": {
      "photographer": "Tima Miroshnichenko",
      "photographerUrl": "https://www.pexels.com/@tima-miroshnichenko",
      "sourceUrl": "https://www.pexels.com/photo/groomer-blow-drying-a-yorkshire-terrier-6131575/",
      "provider": "Pexels",
      "photoId": 6131575
    }
  },
  "featureBooking": {
    "src": "/images/marketing/feature-booking.jpg",
    "width": 1600,
    "height": 1067,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAALABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAQQFBv/EAB0QAQABBQEBAQAAAAAAAAAAAAECAAMEESESInH/xAAUAQEAAAAAAAAAAAAAAAAAAAAB/8QAFhEBAQEAAAAAAAAAAAAAAAAAAQAR/9oADAMBAAIRAxEAPwAGdrB8p0OtJyvEoQ3+1XMe0208Gqz2T8qR4DQqk5l//9k=",
    "alt": "A pet owner booking a groom on their phone with their dog beside them",
    "credit": {
      "photographer": "Anna Galimova",
      "photographerUrl": "https://www.pexels.com/@anna-galimova-81015115",
      "sourceUrl": "https://www.pexels.com/photo/a-woman-sitting-outdoors-with-a-dog-10458497/",
      "provider": "Pexels",
      "photoId": 10458497
    }
  },
  "featureRoute": {
    "src": "/images/marketing/feature-route.jpg",
    "width": 1600,
    "height": 900,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAAD/8QAHRAAAgIBBQAAAAAAAAAAAAAAAQIAAxIEExUxQf/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8A0XX2q43LGAHYEVyoNRWvLPwmEaQhH//Z",
    "alt": "A service van on a quiet suburban street",
    "credit": {
      "photographer": "Artem Podrez",
      "photographerUrl": "https://www.pexels.com/@artempodrez",
      "sourceUrl": "https://www.pexels.com/photo/man-carrying-boxes-beside-a-van-5025669/",
      "provider": "Pexels",
      "photoId": 5025669
    }
  },
  "featureCard": {
    "src": "/images/marketing/feature-card.jpg",
    "width": 1200,
    "height": 1662,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAWABADASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAMBAgQF/8QAIRAAAQMEAQUAAAAAAAAAAAAAAQACBQMEESExEiJBUXH/xAAXAQADAQAAAAAAAAAAAAAAAAAAAQID/8QAFxEBAQEBAAAAAAAAAAAAAAAAAAERQf/aAAwDAQACEQMRAD8Amzmy53SCXOWeSmS92GDu4+JMXY1KFbLsEY58pd/H1DducwaKxkk6vXUI9EqpO95KEJB//9k=",
    "alt": "Portrait of a freshly groomed dog",
    "credit": {
      "photographer": "Helena Lopes",
      "photographerUrl": "https://www.pexels.com/@helenalopes",
      "sourceUrl": "https://www.pexels.com/photo/elegant-poodle-with-flower-outdoors-39609535/",
      "provider": "Pexels",
      "photoId": 39609535
    }
  },
  "cat": {
    "src": "/images/marketing/cat-groom.jpg",
    "width": 1600,
    "height": 1067,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAALABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAgME/8QAHRAAAgICAwEAAAAAAAAAAAAAAQIDEQAhBBJBMf/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AzcaATI5aQKFHuGWGOPiqQ/eS95AMbq9X8xNrXmQf/9k=",
    "alt": "A calm cat being groomed",
    "credit": {
      "photographer": "Tuğba",
      "photographerUrl": "https://www.pexels.com/@tugba",
      "sourceUrl": "https://www.pexels.com/photo/fluffy-cat-grooming-on-rocky-surface-35697928/",
      "provider": "Pexels",
      "photoId": 35697928
    }
  },
  "before": {
    "src": "/images/marketing/before.jpg",
    "width": 1200,
    "height": 1200,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAgUG/8QAHBAAAQUBAQEAAAAAAAAAAAAAAQACAwQREyEx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAgP/xAAWEQADAAAAAAAAAAAAAAAAAAAAEiH/2gAMAwEAAhEDEQA/ANFXstmboIxGxK2MdN8CkMhmlonmS0A+EIWbMraZ6Auz6SovRrD/2Q==",
    "alt": "A dog with overgrown fur before grooming (illustrative)",
    "credit": {
      "photographer": "David Mosquera",
      "photographerUrl": "https://www.pexels.com/@sie7e",
      "sourceUrl": "https://www.pexels.com/photo/white-dog-portrait-18027067/",
      "provider": "Pexels",
      "photoId": 18027067
    }
  },
  "after": {
    "src": "/images/marketing/after.jpg",
    "width": 1200,
    "height": 1200,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABQb/xAAfEAACAgIBBQAAAAAAAAAAAAABAgADBBESBSExQVH/xAAVAQEBAAAAAAAAAAAAAAAAAAADBP/EABYRAAMAAAAAAAAAAAAAAAAAAAARIf/aAAwDAQACEQMRAD8AFu4IiOQeXyN0E52Ol9akMnYwR6brjtV2vqUPRTZjU6caUnxJ3R1D/9k=",
    "alt": "A neatly groomed dog after grooming (illustrative)",
    "credit": {
      "photographer": "Quang Viet Nguyen",
      "photographerUrl": "https://www.pexels.com/@quang-viet-nguyen-107013384",
      "sourceUrl": "https://www.pexels.com/photo/a-cute-dog-wearing-striped-clothes-while-lying-on-the-floor-13073385/",
      "provider": "Pexels",
      "photoId": 13073385
    }
  },
  "bath": {
    "src": "/images/marketing/dog-bath.jpg",
    "width": 1600,
    "height": 1067,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAALABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAQIDBP/EAB8QAAICAQQDAAAAAAAAAAAAAAECAAMRBCEiUTEzQf/EABQBAQAAAAAAAAAAAAAAAAAAAAH/xAAVEQEBAAAAAAAAAAAAAAAAAAAAMf/aAAwDAQACEQMRAD8A2DXEVKUwWPcc3Nc1ZXjnyJK1FWnZQMQL6Fb73Ch//9k=",
    "alt": "A dog enjoying a bath",
    "credit": {
      "photographer": "Alice Castro",
      "photographerUrl": "https://www.pexels.com/@alicedecasttro",
      "sourceUrl": "https://www.pexels.com/photo/bubbles-near-the-brown-and-white-long-coated-dog-14568191/",
      "provider": "Pexels",
      "photoId": 14568191
    }
  }
} as const satisfies Record<string, ImageAsset>;
export type ImageKey = keyof typeof images;
