// Usage:  PEXELS_API_KEY=xxxx node scripts/fetch-images.mjs
// Node 18+. Needs `npm i -D sharp`. Free API key: https://www.pexels.com/api/
import fs from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";
import { slots } from "./images.config.mjs";

const KEY = process.env.PEXELS_API_KEY;
if (!KEY) { console.error("Set PEXELS_API_KEY (free at https://www.pexels.com/api/)"); process.exit(1); }
const API = process.env.PEXELS_API_BASE || "https://api.pexels.com";
const OUT = path.resolve("public/images/marketing");
const GEN = path.resolve("src/content/images.generated.ts");
const PREVIEW = path.resolve("scripts/out/preview.html");
await fs.mkdir(OUT, { recursive: true });
await fs.mkdir(path.dirname(GEN), { recursive: true });
await fs.mkdir(path.dirname(PREVIEW), { recursive: true });

async function search(query, orientation) {
  const url = `${API}/v1/search?query=${encodeURIComponent(query)}&orientation=${orientation}&per_page=40`;
  const r = await fetch(url, { headers: { Authorization: KEY } });
  if (!r.ok) throw new Error(`Pexels API ${r.status} for "${query}"`);
  return (await r.json()).photos ?? [];
}
const sized = (u, w) => (u.includes("images.pexels.com") ? `${u.split("?")[0]}?auto=compress&cs=tinysrgb&w=${w}` : u);

const results = {};
const previewRows = [];
let heroBuf = null;

for (const slot of slots) {
  let chosen = null, usedQuery = null;
  for (const q of slot.queries) {
    try {
      const photos = (await search(q, slot.orientation)).filter((p) => p.width >= slot.minWidth);
      if (photos.length > slot.pick) { chosen = photos[slot.pick]; usedQuery = q; break; }
    } catch (e) { console.warn(`  ! ${e.message}`); }
  }
  if (!chosen) { console.warn(`✗ ${slot.key}: no suitable photo found — edit queries in images.config.mjs`); continue; }

  const res = await fetch(sized(chosen.src.original, slot.width));
  if (!res.ok) { console.warn(`✗ ${slot.key}: download failed (${res.status})`); continue; }
  const input = Buffer.from(await res.arrayBuffer());
  const img = sharp(input).rotate();
  const meta = await img.metadata();
  const outBuf = await img.resize({ width: Math.min(slot.width, meta.width), withoutEnlargement: true })
    .jpeg({ quality: 82, mozjpeg: true }).toBuffer();
  const outMeta = await sharp(outBuf).metadata();
  const blur = await sharp(outBuf).resize(16).blur().jpeg({ quality: 40 }).toBuffer();
  await fs.writeFile(path.join(OUT, `${slot.file}.jpg`), outBuf);
  if (slot.key === "hero") heroBuf = outBuf;

  results[slot.key] = {
    src: `/images/marketing/${slot.file}.jpg`,
    width: outMeta.width, height: outMeta.height,
    blurDataURL: `data:image/jpeg;base64,${blur.toString("base64")}`,
    alt: slot.alt,
    credit: { photographer: chosen.photographer, photographerUrl: chosen.photographer_url, sourceUrl: chosen.url, provider: "Pexels", photoId: chosen.id },
  };
  previewRows.push(`<figure><img src="../../public/images/marketing/${slot.file}.jpg"><figcaption><b>${slot.key}</b> (pick ${slot.pick}, “${usedQuery}”)<br>by <a href="${chosen.photographer_url}">${chosen.photographer}</a> · <a href="${chosen.url}">Pexels page</a></figcaption></figure>`);
  console.log(`✓ ${slot.key} ← ${chosen.photographer} (${chosen.url})`);
}

if (heroBuf) {
  await sharp(heroBuf).resize(1200, 630, { fit: "cover", position: "attention" }).jpeg({ quality: 82 }).toFile(path.resolve("public/og.jpg"));
  console.log("✓ public/og.jpg");
}

const ts = `// AUTO-GENERATED by scripts/fetch-images.mjs — do not edit by hand.
export interface ImageAsset { src: string; width: number; height: number; blurDataURL: string; alt: string;
  credit: { photographer: string; photographerUrl: string; sourceUrl: string; provider: "Pexels"; photoId: number } }
export const images = ${JSON.stringify(results, null, 2)} as const satisfies Record<string, ImageAsset>;
export type ImageKey = keyof typeof images;
`;
await fs.writeFile(GEN, ts);
await fs.writeFile(path.join(OUT, "credits.json"), JSON.stringify(Object.fromEntries(Object.entries(results).map(([k, v]) => [k, v.credit])), null, 2));
await fs.writeFile(PREVIEW, `<!doctype html><meta charset=utf-8><title>Image preview</title><style>body{font:14px system-ui;margin:24px;display:grid;grid-template-columns:repeat(auto-fill,minmax(360px,1fr));gap:20px}img{width:100%;border-radius:12px}figure{margin:0}</style>${previewRows.join("")}`);
console.log(`\nDone. ${Object.keys(results).length}/${slots.length} images.\nOpen scripts/out/preview.html to review. Swap any with "pick" in scripts/images.config.mjs and re-run.`);
